# Generated by Django 3.0.3 on 2020-03-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Channel',
            new_name='Package',
        ),
    ]
