# Generated by Django 3.0.3 on 2020-03-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0002_auto_20200302_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period_TVN_max_min',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('CPP_min', models.IntegerField()),
                ('CPP_max', models.IntegerField()),
            ],
        ),
    ]
