# Generated by Django 3.0.3 on 2020-03-02 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0004_period_tvp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period_CPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('CPP_min', models.IntegerField(null=True)),
                ('CPP_max', models.IntegerField(null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='excel.Station')),
            ],
        ),
        migrations.DeleteModel(
            name='Period_TVN_max_min',
        ),
        migrations.DeleteModel(
            name='Period_TVP',
        ),
    ]
