# Generated by Django 3.0.3 on 2020-03-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0006_period_cpp_cpp'),
    ]

    operations = [
        migrations.AddField(
            model_name='period_cpp',
            name='index_package',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period_cpp',
            name='package',
            field=models.ManyToManyField(to='excel.Package'),
        ),
        migrations.CreateModel(
            name='Period_month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('index_month', models.FloatField()),
                ('month_package', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='excel.Package')),
            ],
        ),
    ]
