# Generated by Django 3.0.3 on 2020-03-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0007_auto_20200303_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period_cpp',
            name='station',
        ),
    ]
