# Generated by Django 3.0.3 on 2020-03-04 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0008_remove_period_cpp_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period_cpp',
            name='package',
        ),
        migrations.AddField(
            model_name='package',
            name='period_cpp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='excel.Period_CPP'),
        ),
    ]
