# Generated by Django 3.0.3 on 2020-03-04 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0009_auto_20200304_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('index_month', models.FloatField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='excel.Station')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('CPP_min', models.IntegerField(null=True)),
                ('CPP_max', models.IntegerField(null=True)),
                ('CPP', models.IntegerField(null=True)),
                ('Station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='excel.Station')),
            ],
        ),
        migrations.RemoveField(
            model_name='period_month',
            name='month_package',
        ),
        migrations.RemoveField(
            model_name='package',
            name='period_cpp',
        ),
        migrations.DeleteModel(
            name='Period_CPP',
        ),
        migrations.DeleteModel(
            name='Period_month',
        ),
    ]
