# Generated by Django 3.0.3 on 2020-03-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0010_auto_20200304_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodyear',
            name='CPP',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='periodyear',
            name='CPP_max',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='periodyear',
            name='CPP_min',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
