# Generated by Django 3.0.3 on 2020-03-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0012_indexpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpackage',
            name='value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
