# Generated by Django 3.0.3 on 2020-03-05 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0013_indexpackage_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexpackage',
            old_name='value',
            new_name='index',
        ),
        migrations.AddField(
            model_name='indexpackage',
            name='pakiet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='excel.Package'),
            preserve_default=False,
        ),
    ]
