# Generated by Django 3.0.3 on 2020-03-05 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0015_auto_20200305_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.FloatField()),
                ('pakiet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='excel.Package')),
                ('period_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='excel.PeriodYear')),
            ],
        ),
    ]
