# Generated by Django 3.0.3 on 2020-03-05 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0016_indexpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpackage',
            name='period_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='excel.PeriodYear'),
        ),
    ]
