# Generated by Django 3.0.3 on 2020-03-06 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0017_auto_20200305_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel.Station'),
        ),
        migrations.AlterField(
            model_name='periodmonth',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel.Station'),
        ),
        migrations.AlterField(
            model_name='periodyear',
            name='Station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel.Station'),
        ),
    ]
